//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("marble.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string Archives {
            get {
                return ResourceManager.GetString("Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book and manuscript.
        /// </summary>
        public static string book_and_manuscript {
            get {
                return ResourceManager.GetString("book-and-manuscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentation center.
        /// </summary>
        public static string documentation_center {
            get {
                return ResourceManager.GetString("documentation-center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents type.
        /// </summary>
        public static string Documents_type {
            get {
                return ResourceManager.GetString("Documents_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijaz.
        /// </summary>
        public static string Hijaz {
            get {
                return ResourceManager.GetString("Hijaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Categories.
        /// </summary>
        public static string Home_archive_categories {
            get {
                return ResourceManager.GetString("Home-archive-categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iraq.
        /// </summary>
        public static string Iraq {
            get {
                return ResourceManager.GetString("Iraq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon.
        /// </summary>
        public static string Lebanon {
            get {
                return ResourceManager.GetString("Lebanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morocco.
        /// </summary>
        public static string Morocco {
            get {
                return ResourceManager.GetString("Morocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other photos.
        /// </summary>
        public static string Other_photos {
            get {
                return ResourceManager.GetString("Other-photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palestine archive.
        /// </summary>
        public static string pal_archive {
            get {
                return ResourceManager.GetString("pal_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestine.
        /// </summary>
        public static string Palestine {
            get {
                return ResourceManager.GetString("Palestine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palestinian newspaper pages.
        /// </summary>
        public static string Palestinian_newspaper_pages {
            get {
                return ResourceManager.GetString("Palestinian-newspaper-pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo document.
        /// </summary>
        public static string photo_document {
            get {
                return ResourceManager.GetString("photo-document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quds.
        /// </summary>
        public static string Quds {
            get {
                return ResourceManager.GetString("Quds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording hour for Palestinian radios.
        /// </summary>
        public static string Recording_hour_for_Palestinian_radios {
            get {
                return ResourceManager.GetString("Recording-hour-for-Palestinian-radios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sham.
        /// </summary>
        public static string Sham {
            get {
                return ResourceManager.GetString("Sham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Documents.
        /// </summary>
        public static string Some_Dodcuments {
            get {
                return ResourceManager.GetString("Some-Dodcuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syria.
        /// </summary>
        public static string Syria {
            get {
                return ResourceManager.GetString("Syria", resourceCulture);
            }
        }
    }
}
