//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marble.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarbleEntities : DbContext
    {
        public MarbleEntities()
            : base("name=MarbleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Design> Designs { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Gallery> Product_Gallery { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Design_Gallery> Design_Gallery { get; set; }
        public virtual DbSet<Project_Gallery> Project_Gallery { get; set; }
        public virtual DbSet<Contact_Form> Contact_Form { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
