//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marble.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Gallery
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> Project_id { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
