//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marble.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Project_Gallery = new HashSet<Project_Gallery>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public Nullable<int> Category_id { get; set; }
        public Nullable<int> Cover_image_id { get; set; }
        public string Cover_Url { set; get; }

        public virtual Category Category { get; set; }
        public virtual Product_Gallery Product_Gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Gallery> Project_Gallery { get; set; }
    }
}
